name: Test XCode build
on:
  push:
jobs:
  test_xcode:
    runs-on: macos-11
    steps:
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: true
          ref: philipn-xcode-build

      - name: Configure
        shell: bash
        run: |
          mkdir -p out/build
          cmake \
            -G Xcode \
            -B out/build \
            -DCMAKE_OSX_ARCHITECTURES="arm64;x86_64" \
            -DBUILD_SHARED_LIBS=OFF \
            -DBMX_BUILD_URIPARSER_SOURCE=ON \
            -DCMAKE_INSTALL_PREFIX:PATH=../install \
            -DLIBMXF_BUILD_EXAMPLES=ON \
            -DLIBMXF_BUILD_TOOLS=ON \
            -DLIBMXFPP_BUILD_EXAMPLES=ON \
            -DLIBMXFPP_BUILD_TOOLS=ON \
            .

      - name: Build
        shell: bash
        run: |
          cmake --build out/build --config Release

      - name: Test
        shell: bash
        run: |
          cd out/build
          ctest --output-on-failure -C Release

      - name: Install
        shell: bash
        run: |
          cmake --build out/build --config Release --target install

      - name: Upload binaries
        uses: actions/upload-artifact@v3
        with:
          name: macos-binaries
          path: |
            out/install
